### ISSUE TITLE
unable to inference

### ISSUE THREAD

**Issue by Dance2MIDI** [theEricMa/DiffSpeaker#4]
Hello, the demo effect of this work is very good. But I keep getting stuck here when I run the inference file：

You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2024-02-20 00:53:36,492 Loading audio from demo/wavs/speech_long.wav
2024-02-20 00:53:38,311 Loading checkpoints from checkpoints/vocaset/diffspeaker_wav2vec2_vocaset.ckpt
2024-02-20 00:53:39,551 Loading template mesh from datasets/vocaset/templates.pkl
2024-02-20 00:53:39,562 Making predictions
  0%|                                                  | 0/2898 [00:00<?, ?it/s

**Comment by theEricMa** [comment]
Hello, the log indicates that the model has completed the inference process and is now proceeding to [render](https://github.com/theEricMa/DiffSpeaker/blob/78f30dbb83222a6138ac381fd298fc395e2d3500/demo_vocaset.py#L169) the anticipated outcome. It seems likely that the issue causing the process to hang is due to an incorrect installation of the [MPI-IS](https://github.com/MPI-IS/mesh) package. To troubleshoot this, consider setting the [multi_process](https://github.com/theEricMa/DiffSpeaker/blob/78f30dbb83222a6138ac381fd298fc395e2d3500/demo_vocaset.py#L169) option to false, which will allow you to run the program in single process mode for easier debugging.

**Comment by matilda1022** [comment]
Ok. I have solved
